# Generated by Django 4.0.3 on 2022-03-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElevationQuery',
            fields=[
                ('time_queried', models.DateTimeField(primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('valid_response', models.BooleanField()),
                ('elevation', models.FloatField(blank=True)),
            ],
        ),
    ]
