# Generated by Django 4.0.3 on 2022-03-15 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ElevationQuery',
        ),
    ]
