# Generated by Django 4.0.3 on 2022-03-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0002_delete_elevationquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElevationQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('is_valid', models.BooleanField()),
                ('elevation', models.FloatField(blank=True)),
            ],
        ),
    ]
