# Generated by Django 4.0.3 on 2022-03-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('lat1', models.FloatField()),
                ('lon1', models.FloatField()),
                ('dist', models.FloatField()),
            ],
        ),
    ]
