# Generated by Django 4.0.3 on 2022-03-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_distancequery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elevationquery',
            name='is_valid',
        ),
        migrations.AddField(
            model_name='distancequery',
            name='lat2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='distancequery',
            name='lon2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='distancequery',
            name='dist',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='distancequery',
            name='lat1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='distancequery',
            name='lon1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='elevationquery',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='elevationquery',
            name='lon',
            field=models.FloatField(default=0),
        ),
    ]
